title: Karthik Kulkarni
logo: /assets/img/ProfilePic.png
#description: text below image
show_downloads: false
theme: jekyll-theme-minimal

# Contact information
contact:
  linkedin:
    username: https://www.linkedin.com/in/karthik-kulkarni/
    logo: /assets/img/Linkedin.jpg
  email: karthik93kulkarni@gmail.com
    logo: /assets/img/gmail.png
  phone: +480-438-5191
    logo: /assets/img/phone.png